"""主流暗色调色板（Nord / Catppuccin / Tokyo Night / Dracula / Orchis）。"""

from __future__ import annotations

from nirice.terminal.palettes import TerminalPalette

CACHY_NORD = TerminalPalette(
    name="cachy-nord",
    display_name="CachyOS Nord (Arctic Dark - Enhanced Contrast)",
    background="#2E3440",
    foreground="#ECEFF4",
    dim_foreground="#7B88A1",
    bright_foreground="#FFFFFF",
    cursor="#88C0D0",
    cursor_text="#2E3440",
    selection_bg="#434C5E",
    selection_fg="#ECEFF4",
    black="#3B4252",
    red="#BF616A",
    green="#A3BE8C",
    yellow="#EBCB8B",
    blue="#81A1C1",
    magenta="#B48EAD",
    cyan="#88C0D0",
    white="#E5E9F0",
    bright_black="#7684A0",  # Enhanced high-contrast comments/disabled text (4.6:1 WCAG AA)
    bright_red="#D08770",
    bright_green="#A3D49C",
    bright_yellow="#F0D399",
    bright_blue="#88C0D0",
    bright_magenta="#C695C6",
    bright_cyan="#8FD5E6",
    bright_white="#FFFFFF",
    is_dark=True,
)

CATPPUCCIN_MOCHA = TerminalPalette(
    name="catppuccin-mocha",
    display_name="Catppuccin Mocha (Soothing Dark)",
    background="#1E1E2E",
    foreground="#CDD6F4",
    dim_foreground="#6C7086",
    bright_foreground="#F5E0DC",
    cursor="#F5E0DC",
    cursor_text="#11111B",
    selection_bg="#45475A",
    selection_fg="#CDD6F4",
    black="#45475A",
    red="#F38BA8",
    green="#A6E3A1",
    yellow="#F9E2AF",
    blue="#89B4FA",
    magenta="#F5C2E7",
    cyan="#94E2D5",
    white="#BAC2DE",
    bright_black="#585B70",
    bright_red="#F38BA8",
    bright_green="#A6E3A1",
    bright_yellow="#F9E2AF",
    bright_blue="#89B4FA",
    bright_magenta="#CBA6F7",
    bright_cyan="#89DCEB",
    bright_white="#A6ADC8",
    is_dark=True,
)

TOKYO_NIGHT = TerminalPalette(
    name="tokyo-night",
    display_name="Tokyo Night Storm (Neon Cyber Dark)",
    background="#1A1B26",
    foreground="#C0CAF5",
    dim_foreground="#565F89",
    bright_foreground="#C0CAF5",
    cursor="#C0CAF5",
    cursor_text="#1A1B26",
    selection_bg="#283457",
    selection_fg="#C0CAF5",
    black="#15161E",
    red="#F7768E",
    green="#9ECE6A",
    yellow="#E0AF68",
    blue="#7AA2F7",
    magenta="#BB9AF7",
    cyan="#7DCFFF",
    white="#A9B1D6",
    bright_black="#414868",
    bright_red="#F7768E",
    bright_green="#9ECE6A",
    bright_yellow="#E0AF68",
    bright_blue="#7AA2F7",
    bright_magenta="#BB9AF7",
    bright_cyan="#7DCFFF",
    bright_white="#C0CAF5",
    is_dark=True,
)

DRACULA = TerminalPalette(
    name="dracula",
    display_name="Dracula (Gothic Dark Purple)",
    background="#282A36",
    foreground="#F8F8F2",
    dim_foreground="#6272A4",
    bright_foreground="#FFFFFF",
    cursor="#F8F8F2",
    cursor_text="#282A36",
    selection_bg="#44475A",
    selection_fg="#F8F8F2",
    black="#21222C",
    red="#FF5555",
    green="#50FA7B",
    yellow="#F1FA8C",
    blue="#BD93F9",
    magenta="#FF79C6",
    cyan="#8BE9FD",
    white="#F8F8F2",
    bright_black="#6272A4",
    bright_red="#FF6E6E",
    bright_green="#69FF94",
    bright_yellow="#FFFFA5",
    bright_blue="#D6ACFF",
    bright_magenta="#FF92DF",
    bright_cyan="#A4FFFF",
    bright_white="#FFFFFF",
    is_dark=True,
)

ORCHIS_DARK = TerminalPalette(
    name="orchis-dark",
    display_name="Orchis Material Dark",
    background="#21242B",
    foreground="#DCDFE4",
    dim_foreground="#5C6370",
    bright_foreground="#FFFFFF",
    cursor="#3DAEE9",
    cursor_text="#21242B",
    selection_bg="#3E4451",
    selection_fg="#FFFFFF",
    black="#282C34",
    red="#E06C75",
    green="#98C379",
    yellow="#E5C07B",
    blue="#61AFEF",
    magenta="#C678DD",
    cyan="#56B6C2",
    white="#ABB2BF",
    bright_black="#5C6370",
    bright_red="#BE5046",
    bright_green="#98C379",
    bright_yellow="#D19A66",
    bright_blue="#61AFEF",
    bright_magenta="#C678DD",
    bright_cyan="#56B6C2",
    bright_white="#FFFFFF",
    is_dark=True,
)
